# Programming_Assingment8

### 1.	Write a Python Program to Add Two Matrices

In [7]:
# two matrices can be added only if their dimensions are same.
# lets consider both the matrices have same dimensions

x = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]

y = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]

result = [[x[i][j] + y[i][j] for j in range(len(x[0]))] for i in range(len(x))]

print(f"x= {x}")
print(f"y= {y}")
print(f"Addition of above two matrices are: \n {result}")

x= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
y= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Addition of above two matrices are: 
 [[2, 4, 6], [8, 10, 12], [14, 16, 18]]


### 2.Write a Python Program to Multiply Two Matrices?

In [78]:
# The product of two matrices will be defined 
# if the number of columns in the first matrix 
# is equal to 
# the number of rows in the second matrix

x = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]

y = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]

r = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]

#-------------------- without using numpy 
print("Two matrix product without using numpy: ")
for i in range(len(x)): # rows of x
    for j in range(len(y[0])): # columns of y
        for k in range(len(y)): # rows of y
            r[i][j] = r[i][j] + (x[i][k] * y[k][j])    
print(r)

#-------------------- using numpy 
print("Two matrix product using numpy: ")
import numpy as np
z = np.dot(x,y)
print(z)

Two matrix product without using numpy: 
[[30, 36, 42], [66, 81, 96], [102, 126, 150]]
Two matrix product using numpy: 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


### 3.Write a Python Program to Transpose a Matrix

In [79]:
x = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
print("Original matrix:\n", x)

print("Matrix transpose using numpy: ")
print(np.transpose(x))


print("Matrix transpose without using numpy: ")
t_x =  [ [x[j][i] for j in range(len(x[0]))] for i in range(len(x)) ]
print(t_x)

Original matrix:
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Matrix transpose using numpy: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Matrix transpose without using numpy: 
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


### 4.Write a Python Program to Sort Words in Alphabetic Order

In [80]:
in_str = "This is the Example string has Case sensitive words to sort the words in Alphabetic and alphabetic order Order"
# convert all the words to lower case and sort
words = in_str.lower().split()
words.sort()
print("Before alphabetical sort: \n", in_str )
print("After alphabetical sort: \n", ' '.join(words))

Before alphabetical sort: 
 This is the Example string has Case sensitive words to sort the words in Alphabetic and alphabetic order Order
After alphabetical sort: 
 alphabetic alphabetic and case example has in is order order sensitive sort string the the this to words words


### 5.Write a Python Program to Remove Punctuation From a String

In [81]:
import string
print("All available punctuations are: \n", string.punctuation)

#make use of """ """ to define string bcoz punctuation includes " and '
s = """a!b"c#d$e%f&g'h(i)j*k+l,m-n.q/p:r;s<t=u>v?w@x[y\z]a^b_c`d{e|f}g~h"""
finalStr = ""
for i in s :
    if i not in string.punctuation:
        finalStr = finalStr + i
print("String before removing the punctuaitons is: \n", s)
print("String after removing the punctuaitons is: \n", finalStr)

All available punctuations are: 
 !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
String before removing the punctuaitons is: 
 a!b"c#d$e%f&g'h(i)j*k+l,m-n.q/p:r;s<t=u>v?w@x[y\z]a^b_c`d{e|f}g~h
String after removing the punctuaitons is: 
 abcdefghijklmnqprstuvwxyzabcdefgh
